Repository siemens/ix, pull requests merged in 2023-09, with the labels that each got.

#733 docs(figma): integrate figma api
  .github/workflows/deploy-pages-daily.yml
  .github/workflows/deploy-pages.yml
  .gitignore
  README.md
  package.json
  packages/documentation/docs/controls/_button_styleguide.md
  packages/documentation/docusaurus.config.js
  packages/documentation/package.json
  packages/documentation/static/img/figma_error.png
  packages/figma-plugin/figma.js
  packages/figma-plugin/index.js
  packages/figma-plugin/package.json
  turbo.json
  yarn.lock
Labels: component: documentation

#738 [IxSelect]: Support for Angular Forms
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/select-ng-model.ts
  packages/angular/src/components.ts
  packages/angular/src/index.ts
  packages/angular/src/module.ts
  packages/angular/src/select-value-accessor.ts
  packages/angular/src/value-accessor.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/select/select.tsx
  packages/core/src/components/select/test/select.ct.ts
  packages/core/stencil.config.ts
  packages/documentation/docs/controls/select.md
  packages/vue/src/components.ts
Labels: semvers: minor

#739 fix(core/styles): reduce css file size
  packages/core/package.json
  packages/core/scripts/build/build-css.ts
  packages/core/scss/_core.scss
  packages/core/scss/ix-core.scss
  packages/core/scss/ix.scss
  packages/documentation/docs/guidelines/theme.md
  yarn.lock
Labels: semvers: patch

#753 fix(core): overwrite custom icon coloring
  packages/core/src/components/button/button-mixin.scss
Labels: semvers: patch

#752 refactor(core/layout-grid): rename to layout grid
  packages/angular-test-app/src/preview-examples/grid-padding.html
  packages/angular-test-app/src/preview-examples/grid-padding.ts
  packages/angular-test-app/src/preview-examples/grid-size.html
  packages/angular-test-app/src/preview-examples/grid-size.ts
  packages/angular-test-app/src/preview-examples/grid.html
  packages/angular-test-app/src/preview-examples/grid.ts
  packages/angular-test-app/src/preview-examples/theme-switcher.html
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/col/col.scss
  packages/core/src/components/col/col.tsx
  packages/core/src/components/grid/layout-grid.scss
  packages/core/src/components/grid/layout-grid.tsx
  packages/core/src/components/row/row.scss
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-large-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-large-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-medium-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-medium-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-small-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/layout-grid/layout-grid.e2e.ts-snapshots/should-not-have-regression-small-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/layout-grid.md
  packages/html-test-app/src/preview-examples/grid-padding.html
  packages/html-test-app/src/preview-examples/grid-size.html
  packages/html-test-app/src/preview-examples/grid.html
  packages/html-test-app/src/preview-examples/theme-switcher.html
  packages/react-test-app/src/preview-examples/grid-padding.tsx
  packages/react-test-app/src/preview-examples/grid-size.tsx
  packages/react-test-app/src/preview-examples/grid.tsx
  packages/react-test-app/src/preview-examples/theme-switcher.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/preview-examples/grid-padding.vue
  packages/vue-test-app/src/preview-examples/grid-size.vue
  packages/vue-test-app/src/preview-examples/grid.css
  packages/vue-test-app/src/preview-examples/grid.vue
  packages/vue/src/components.ts
Labels: semvers: major

#723 feat(core/slider): add slider component
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/slider-error.html
  packages/angular-test-app/src/preview-examples/slider-error.ts
  packages/angular-test-app/src/preview-examples/slider-marker.html
  packages/angular-test-app/src/preview-examples/slider-marker.ts
  packages/angular-test-app/src/preview-examples/slider-trace.html
  packages/angular-test-app/src/preview-examples/slider-trace.ts
  packages/angular-test-app/src/preview-examples/slider.html
  packages/angular-test-app/src/preview-examples/slider.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/slider/slider.scss
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/slider/test/slider.ct.ts
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/src/components/utils/a11y.ts
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/slider/slider.e2e.ts
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-marker-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-marker-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-error-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-error-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-label-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-label-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-min-max-changes-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-render-with-min-max-changes-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-show-reference-value-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/slider/slider.e2e.ts-snapshots/should-show-reference-value-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/layout-grid.md
  packages/documentation/docs/controls/slider.md
  packages/html-test-app/src/preview-examples/slider-error.html
  packages/html-test-app/src/preview-examples/slider-marker.html
  packages/html-test-app/src/preview-examples/slider-trace.html
  packages/html-test-app/src/preview-examples/slider.html
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/slider-error.tsx
  packages/react-test-app/src/preview-examples/slider-marker.tsx
  packages/react-test-app/src/preview-examples/slider-trace.tsx
  packages/react-test-app/src/preview-examples/slider.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/slider-error.vue
  packages/vue-test-app/src/preview-examples/slider-marker.vue
  packages/vue-test-app/src/preview-examples/slider-trace.vue
  packages/vue-test-app/src/preview-examples/slider.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#763 chore: update to ix-icons 1.2.0
  packages/angular-test-app/package.json
  packages/angular/package.json
  packages/core/package.json
  packages/core/src/components/breadcrumb-item/breadcrumb-item.scss
  packages/core/src/components/icon-button/test/icon-button.ct.ts
  packages/core/src/tests/split-button/split-button.e2e.ts
  packages/documentation/package.json
  packages/html-test-app/package.json
  packages/react-test-app/package.json
  packages/react/package.json
  packages/vue-test-app/package.json
  packages/vue/package.json
  packages/vue/src/components.ts
  yarn.lock
Labels: semvers: major

#762 chore(core): remove deprecated props/events
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/chip/chip.tsx
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/event-list-item/event-list-item.tsx
  packages/core/src/components/menu-item/menu-item.tsx
  packages/vue/src/components.ts
Labels: semvers: major

#761 feat(core/dropdown-item): mark dropdown-item as internal event
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/documentation/docs/controls/dropdown.md
Labels: semvers: major

#760 fix(core/split-button-item): deprecate component
  BREAKING_CHANGES.md
  packages/angular-test-app/src/preview-examples/split-button-icons.ts
  packages/angular-test-app/src/preview-examples/split-button.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/split-button-item/split-button-item.tsx
  packages/core/src/components/split-button/split-button.tsx
  packages/core/src/tests/split-button/basic/index.html
  packages/documentation/docs/controls/split-button.md
  packages/html-test-app/src/preview-examples/split-button-icons.html
  packages/html-test-app/src/preview-examples/split-button.html
  packages/react-test-app/src/preview-examples/split-button-icons.tsx
  packages/react-test-app/src/preview-examples/split-button.tsx
  packages/vue-test-app/src/preview-examples/split-button-icons.vue
  packages/vue-test-app/src/preview-examples/split-button.vue
Labels: semvers: patch

#758 fix(core/select): fix editable mode with shadow DOM
  packages/core/src/components/select/select.tsx
  packages/core/src/components/select/test/select.ct.ts
Labels: semvers: minor

#745 feat(core/toggle): support for angular forms
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/toggle-ng-model.ts
  packages/angular/src/boolean-value-accessor.ts
  packages/angular/src/index.ts
  packages/angular/src/module.ts
  packages/core/stencil.config.ts
  packages/documentation/docs/controls/toggle.md
Labels: semvers: minor

#767 feat(core/blind): add variant property
  packages/angular-test-app/src/preview-examples/blind-variants.html
  packages/angular-test-app/src/preview-examples/blind-variants.ts
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/tests/blind/basic/index.html
  packages/core/src/tests/blind/blind.e2e.ts
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/sublabel/index.html
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/_blind_code.md
  packages/html-test-app/src/preview-examples/blind-header-actions.html
  packages/html-test-app/src/preview-examples/blind-variants.html
  packages/react-test-app/src/preview-examples/blind-variants.tsx
  packages/vue-test-app/src/preview-examples/blind-variants.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#782 fix(core/toast): delay inital rendering of toast to next tick
  packages/core/src/components/toast/toast-container.tsx
  packages/core/src/components/toast/toast.scss
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-position-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-position-1-chromium---theme-classic-light-linux.png
  packages/react-test-app/src/main.tsx
  turbo.json
Labels: semvers: patch
