Repository siemens/ix, pull requests merged in 2023-08, with the labels that each got.

#663 feat(core/upload): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/upload/upload.scss
  packages/core/src/components/upload/upload.tsx
Labels: semvers: major

#670 feat(core/select): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/filter-chip/filter-chip.scss
  packages/core/src/components/filter-chip/filter-chip.tsx
  packages/core/src/components/select-item/select-item.tsx
  packages/core/src/components/select-item/test/select-item.spec.tsx
  packages/core/src/components/select/select.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/components/select/test/select.ct.ts
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-select-Index-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-select-Index-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-select-multiple-index-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-select-multiple-index-1-chromium---theme-classic-light-linux.png
Labels: semvers: major

#671 feat(core/validation-tooltip): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/validation-tooltip/validation-tooltip.tsx
Labels: semvers: major

#672 feat(core/tree): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/tree-item/tree-item.scss
  packages/core/src/components/tree-item/tree-item.tsx
  packages/core/src/components/tree/test/tree.ct.ts
  packages/core/src/components/tree/tree.tsx
Labels: semvers: major

#673 feat(core/input-group): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/input-group/input-group.scss
  packages/core/src/components/input-group/input-group.tsx
  packages/core/src/components/input-group/test/input-group.spec.tsx
Labels: semvers: major

#669 feat(core/tabs): add additional navigation events
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/tab-item/tab-item.tsx
  packages/core/src/components/tabs/tabs.tsx
  packages/core/src/components/tabs/test/tabs.ct.ts
  packages/vue/src/components.ts
Labels: semvers: minor

#676 refactor(core/animated-tabs): remove animated-tabs
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/animated-tab/animated-tab.scss
  packages/core/src/components/animated-tab/animated-tab.tsx
  packages/core/src/components/animated-tabs/animated-tabs.scss
  packages/core/src/components/animated-tabs/animated-tabs.tsx
  packages/core/stencil.config.ts
  packages/html-test-app/src/preview-examples/animated-tabs.html
  packages/react/src/components.ts
  packages/vue/src/components.ts
Labels: semvers: major

#678 feat(core/pagination): migrate to shadow dom
  BREAKING_CHANGES.md
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/core/component-doc.json
  packages/core/src/components/icon-button/icon-button-mixin.scss
  packages/core/src/components/pagination/pagination.scss
  packages/core/src/components/pagination/pagination.tsx
  packages/core/src/components/pagination/test/pagination.spec.tsx
  packages/core/src/tests/pagination/basic/index.html
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-light-linux.png
Labels: semvers: major

#679 feat(core/breadcrumb): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/breadcrumb-item/breadcrumb-item.scss
  packages/core/src/components/breadcrumb-item/breadcrumb-item.tsx
  packages/core/src/components/breadcrumb/breadcrumb.scss
  packages/core/src/components/breadcrumb/breadcrumb.tsx
  packages/core/src/components/breadcrumb/test/__snapshots__/cw-breadcrumb.spec.tsx.snap
  packages/core/src/components/breadcrumb/test/cw-breadcrumb.spec.tsx
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-light-linux.png
Labels: semvers: major

#680 feat(core/flip-tile): migrate to shadow dom
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/flip-tile-content/flip-tile-content.tsx
  packages/core/src/components/flip-tile/flip-tile.scss
  packages/core/src/components/flip-tile/flip-tile.tsx
  packages/core/src/components/flip-tile/test/flip-tile.ct.ts
  packages/vue/src/components.ts
Labels: semvers: major

#685 feat(core/menu): provide keyboard navigation
  packages/core/src/components/menu-avatar/menu-avatar.scss
  packages/core/src/components/menu-avatar/menu-avatar.tsx
  packages/core/src/components/menu-category/test/menu-category.ct.ts
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/components/menu-item/menu-item.tsx
  packages/core/src/components/menu-item/test/menu-item.spec.tsx
  packages/core/src/components/menu/test/menu.ct.ts
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#684 refactor(core/select): change itemSelectionChange event signature
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/select/select.tsx
Labels: semvers: major

#689 fix(core/menu): a-tag styling
  packages/core/src/components/menu-category/menu-category.scss
  packages/core/src/components/menu-category/menu-category.tsx
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/components/menu-item/menu-item.tsx
  packages/core/src/tests/menu/menu.e2e.ts
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#688 feat(core/breadcrumb): add keyboard navigation
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/breadcrumb-item/breadcrumb-item.scss
  packages/core/src/components/breadcrumb-item/breadcrumb-item.tsx
  packages/core/src/components/breadcrumb/breadcrumb.scss
  packages/core/src/components/breadcrumb/breadcrumb.tsx
  packages/core/src/components/breadcrumb/test/__snapshots__/cw-breadcrumb.spec.tsx.snap
  packages/core/src/components/breadcrumb/test/breadcrumb.ct.ts
  packages/core/src/components/breadcrumb/test/cw-breadcrumb.spec.tsx
  packages/core/src/components/button/base-button.tsx
  packages/core/src/components/button/button-mixin.scss
  packages/core/src/components/button/button.tsx
  packages/core/src/components/icon-button/icon-button.tsx
  packages/core/src/tests/breadcrumb/basic/index.html
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/breadcrumb/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-light-linux.png
  packages/vue/src/components.ts
Labels: semvers: major

#692 fix(core/modal): allow dialog to overflow
  packages/core/src/components.d.ts
  packages/core/src/components/button/base-button.tsx
  packages/core/src/components/button/button-mixin.scss
  packages/core/src/components/button/button.tsx
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/modal/modal.scss
  packages/core/src/tests/modal/modal.e2e.ts
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-with-dropdown-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-with-dropdown-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/modal/overflow/index.html
  packages/vue/src/components.ts
Labels: semvers: patch

#694 fix(core/dropdownbutton): dropdown alignment
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown-button/dropdown-button.scss
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/documentation/src/components/SwitchTheme.tsx
  packages/vue/src/components.ts
  yarn.lock
Labels: semvers: patch

#696 fix(core/pushcard): use std-text as default color
  packages/core/src/components/card-accordion/card-accordion.scss
Labels: semvers: patch

#690 fix(core/blind): remove blind content after collapse changed
  packages/core/src/components/blind/blind.tsx
Labels: semvers: patch

#707 feat(core/map-navigation-overlay): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/dropdown/test/dropdown.spec.tsx
  packages/core/src/components/event-list/test/event-list.spec.tsx
  packages/core/src/components/expanding-search/test/expanding-search.spec.tsx
  packages/core/src/components/map-navigation-overlay/map-navigation-overlay.scss
  packages/core/src/components/map-navigation-overlay/map-navigation-overlay.tsx
  packages/core/src/components/map-navigation-overlay/test/__snapshots__/map-navigation-overlay.spec.tsx.snap
  packages/core/src/components/map-navigation-overlay/test/map-navigation-overlay.spec.tsx
  packages/core/src/components/map-navigation/test/__snapshots__/map-navigation.spec.tsx.snap
  packages/core/src/components/map-navigation/test/map-navigation.spec.tsx
  packages/core/src/components/menu-item/test/menu-item.spec.tsx
  packages/core/src/components/menu/menu.scss
  packages/core/src/components/menu/menu.tsx
  packages/core/src/components/workflow-steps/test/workflow-steps.spec.ts
Labels: semvers: major

#714 fix(angular): fix change detection on modal when using a TemplateRef
  packages/angular/src/modal/modal.config.ts
  packages/angular/src/modal/modal.service.spec.ts
  packages/angular/src/modal/modal.service.ts
Labels: semvers: patch

#710 fix(core/split-button): prevent inner event to bubble up
  packages/core/src/components/split-button-item/split-button-item.tsx
  packages/core/src/components/split-button/split-button.tsx
Labels: semvers: patch

#719 fix(aggrid): use default font fallbacks from core
  packages/aggrid/scss/ix-aggrid.scss
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-basic-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-basic-1-chromium---theme-classic-light-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-light-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-filter-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-filter-1-chromium---theme-classic-light-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-pagination-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-pagination-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#717 feat(core/input): add basic input styling
  packages/aggrid/scss/ix-aggrid.scss
  packages/angular-test-app/src/preview-examples/validation.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/scripts/e2e/load-e2e-runtime.js
  packages/core/scss/components/_checkboxes.scss
  packages/core/scss/components/_fonts.scss
  packages/core/scss/components/form/_input.scss
  packages/core/scss/ix-core.scss
  packages/core/scss/ix.scss
  packages/core/scss/mixins/_fonts.scss
  packages/core/src/components.d.ts
  packages/core/src/components/category-filter/category-filter.scss
  packages/core/src/components/form-field/form-field.scss
  packages/core/src/components/form-field/form-field.tsx
  packages/core/src/components/input-group/input-group.scss
  packages/core/src/components/input-group/input-group.tsx
  packages/core/src/components/time-picker/time-picker.scss
  packages/core/src/components/typography/typography.scss
  packages/core/src/components/utils/shadow-dom.ts
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/checkbox/checkbox.e2e.ts-snapshots/checkbox-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/checkbox/checkbox.e2e.ts-snapshots/checkbox-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/checkbox/checkbox.e2e.ts-snapshots/checkbox-indeterminate-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/checkbox/checkbox.e2e.ts-snapshots/checkbox-indeterminate-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/input-group/input-group.e2e.ts-snapshots/input-group-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/input-group/input-group.e2e.ts-snapshots/input-group-basic-1-chromium---theme-classic-light-linux.png
  packages/core/stencil.config.ts
  packages/html-test-app/src/preview-examples/validation.html
  packages/react-test-app/src/preview-examples/validation.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/preview-examples/validation.vue
  packages/vue/src/components.ts
Labels: semvers: major

#725 fix(core): update classic theme
  packages/core/scss/theme/classic-dark/_boxShadow.scss
  packages/core/scss/theme/classic-dark/_fontSizes.scss
  packages/core/scss/theme/classic-dark/_index.scss
  packages/core/scss/theme/classic-dark/_letterSpacing.scss
  packages/core/scss/theme/classic-dark/_lineHeights.scss
  packages/core/scss/theme/classic-light/_boxShadow.scss
  packages/core/scss/theme/classic-light/_fontSizes.scss
  packages/core/scss/theme/classic-light/_index.scss
  packages/core/scss/theme/classic-light/_letterSpacing.scss
  packages/core/scss/theme/classic-light/_lineHeights.scss
  packages/core/scss/theme/legacy-classic-dark/_fontSizes.scss
  packages/core/scss/theme/legacy-classic-dark/_index.scss
  packages/core/scss/theme/legacy-classic-dark/_letterSpacing.scss
  packages/core/scss/theme/legacy-classic-dark/_lineHeights.scss
  packages/core/scss/theme/legacy-classic-light/_fontSizes.scss
  packages/core/scss/theme/legacy-classic-light/_index.scss
  packages/core/scss/theme/legacy-classic-light/_letterSpacing.scss
  packages/core/scss/theme/legacy-classic-light/_lineHeights.scss
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/fonts/basic/index.html
  packages/core/src/tests/fonts/fonts.e2e.ts
  packages/core/src/tests/fonts/fonts.e2e.ts-snapshots/fonts-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/fonts/fonts.e2e.ts-snapshots/fonts-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-with-dropdown-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch
