Repository siemens/ix, pull requests merged in 2023-06, with the labels that each got.

#571 fix(core/basic-navigation): increase content width to 100%
  packages/core/src/components/basic-navigation/basic-navigation.scss
  packages/core/src/components/my-component/my-component.scss
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/content-width/index.html
  packages/core/src/tests/map-navigation/content-width/index.html
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-content-width-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#552 feat(core/dropdown): enable shadow dom
  packages/core/component-doc.json
  packages/core/scss/components/_dropdown.scss
  packages/core/src/components/dropdown-item/dropdown-item.scss
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/core/src/components/dropdown/dropdown.scss
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/__snapshots__/dropdown.spec.tsx.snap
  packages/core/src/components/dropdown/test/dropdown.spec.tsx
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/components/select-item/select-item.scss
  packages/core/src/components/select-item/test/select-item.spec.tsx
Labels: semvers: patch

#549 feat(core/tile): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components/tile/tile.scss
  packages/core/src/components/tile/tile.tsx
Labels: semvers: patch

#561 docs(tooltip): make example more common
  packages/angular-test-app/src/preview-examples/tooltip.html
  packages/html-test-app/src/preview-examples/tooltip.html
  packages/react-test-app/src/preview-examples/tooltip.tsx
  packages/vue-test-app/src/preview-examples/tooltip.vue
Labels: component: documentation

#551 feat(core/workflow): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/components/workflow-step/workflow-step.scss
  packages/core/src/components/workflow-step/workflow-step.tsx
  packages/core/src/components/workflow-steps/workflow-steps.scss
  packages/core/src/components/workflow-steps/workflow-steps.tsx
Labels: semvers: patch

#574 docs(migration): remove direct repository link
  packages/documentation/docs/migration/core-ui.md
Labels: component: documentation

#575 chore: update @siemens/ix-icons to 1.1.1
  yarn.lock
Labels: semvers: patch

#565 feat(core/event-list): enable shadow dom
  packages/core/component-doc.json
  packages/core/scss/mixins/shadow-dom/_host-disabled.scss
  packages/core/src/components.d.ts
  packages/core/src/components/event-list-item/event-list-item.scss
  packages/core/src/components/event-list-item/event-list-item.tsx
  packages/core/src/components/event-list/event-list.scss
  packages/core/src/components/event-list/event-list.tsx
  packages/core/src/components/event-list/test/event-list.spec.tsx
  packages/core/src/tests/event-list/chevron/index.html
  packages/core/src/tests/event-list/custom-height/index.html
  packages/core/src/tests/event-list/event-list.e2e.ts-snapshots/event-list-custom-height-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/event-list/event-list.e2e.ts-snapshots/event-list-custom-height-1-chromium---theme-classic-light-linux.png
Labels: semvers: minor

#586 feat(core/datetime-picker): enable shadow dom
  packages/core/component-doc.json
  packages/core/scss/components/_forms.scss
  packages/core/src/components/date-picker/date-picker.scss
  packages/core/src/components/date-picker/date-picker.tsx
  packages/core/src/components/date-time-card/date-time-card.scss
  packages/core/src/components/date-time-card/date-time-card.tsx
  packages/core/src/components/datetime-picker/datetime-picker.scss
  packages/core/src/components/datetime-picker/datetime-picker.tsx
  packages/core/src/components/time-picker/time-picker.scss
  packages/core/src/components/time-picker/time-picker.tsx
Labels: semvers: minor

#590 docs(introduction): update intro page
  packages/documentation/docs/introduction.md
  packages/documentation/docs/team.md
Labels: component: documentation

#597 docs(community): add community links
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: component: documentation

#594 feat(core/tabs): enable shadowDOM
  packages/core/component-doc.json
  packages/core/src/components/tab-item/tab-item.scss
  packages/core/src/components/tab-item/tab-item.tsx
  packages/core/src/components/tab-item/test/tab-item.spec.tsx
  packages/core/src/components/tabs/tabs.scss
  packages/core/src/components/tabs/tabs.tsx
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-overflow-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-rounded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tabs/tabs.e2e.ts-snapshots/tabs-rounded-1-chromium---theme-classic-light-linux.png
Labels: semvers: minor

#600 fix(aggrid): remove box shadow from editor cells
  packages/aggrid/scss/ix-aggrid.scss
  packages/aggrid/src/components/tests/aggrid.e2e.ts
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/src/components/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-light-linux.png
  packages/aggrid/src/components/tests/basic.html
Labels: semvers: patch

#599 fix(core/dropdown-button): deprecate unused property active
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown-button/dropdown-button.tsx
Labels: semvers: patch

#601 docs(overview): rename intro doc
  packages/documentation/docs/controls/_button_code.md
  packages/documentation/docs/introduction.md
Labels: component: documentation

#602 feat(core/filter-chip): enable shadow dom
  packages/core/component-doc.json
  packages/core/scss/mixins/_hover.scss
  packages/core/src/components/filter-chip/filter-chip.scss
  packages/core/src/components/filter-chip/filter-chip.tsx
Labels: semvers: minor

#604 build(docs): ignore new lines of copyright header replacement
  packages/documentation/scripts/generate-api.ts
Labels: component: documentation

#607 feat(core/split-button): migrate to shadow DOM
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/button/button.scss
  packages/core/src/components/split-button-item/split-button-item.css
  packages/core/src/components/split-button-item/split-button-item.tsx
  packages/core/src/components/split-button/split-button.scss
  packages/core/src/components/split-button/split-button.tsx
  packages/core/src/tests/split-button/split-button.e2e.ts
  packages/vue/src/components.ts
Labels: semvers: major

#580 feat(core/link-button): new Link Button component
  packages/angular-test-app/src/preview-examples/link-button-disabled.ts
  packages/angular-test-app/src/preview-examples/link-button.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/link-button/link-button.scss
  packages/core/src/components/link-button/link-button.tsx
  packages/core/src/tests/link-button/basic/index.html
  packages/core/src/tests/link-button/link-button.e2e.ts
  packages/core/src/tests/link-button/link-button.e2e.ts-snapshots/link-button-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/link-button/link-button.e2e.ts-snapshots/link-button-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/link-button/link-button.e2e.ts-snapshots/link-button-truncate-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/link-button/link-button.e2e.ts-snapshots/link-button-truncate-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/link-button/truncate/index.html
  packages/documentation/docs/controls/link-button.md
  packages/html-test-app/src/preview-examples/link-button-disabled.html
  packages/html-test-app/src/preview-examples/link-button.html
  packages/react-test-app/src/preview-examples/link-button-disabled.tsx
  packages/react-test-app/src/preview-examples/link-button.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/preview-examples/link-button-disabled.vue
  packages/vue-test-app/src/preview-examples/link-button.vue
  packages/vue/src/components.ts
Labels: semvers: minor
