Repository siemens/ix, pull requests merged in 2023-03, with the labels that each got.

#410 fix(core/eventlist): selected active/hover effect and visual regression test
  packages/core/src/components/event-list-item/event-list-item.scss
  packages/core/src/components/group/group.scss
  packages/core/src/tests/event-list/event-list.e2e.ts
  packages/core/src/tests/event-list/event-list.e2e.ts-snapshots/event-list-hover-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/event-list/event-list.e2e.ts-snapshots/event-list-hover-1-chromium---theme-classic-light-linux.png
Labels: type: bug

#414 docs(DocTabs): change to button style
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/date-picker/date-picker.tsx
  packages/documentation/docs/controls/modal.md
  packages/documentation/docs/theming/theme.md
  packages/documentation/scripts/renderer/api-renderer.ts
  packages/documentation/src/components/ApiTable/ApiTable.css
  packages/documentation/src/components/ApiTable/index.tsx
  packages/documentation/src/components/ApiTableTag/ApiTableTag.css
  packages/documentation/src/components/ApiTableTag/index.tsx
  packages/documentation/src/components/DocsTabs/DocsTabs.scss
  packages/documentation/src/components/DocsTabs/index.tsx
  packages/documentation/src/css/custom.css
Labels: component: documentation

#412 docs: update description breadcrumb
  packages/documentation/docs/controls/_breadcrumb_code.md
  packages/documentation/docs/controls/_breadcrumb_styleguide.md
  packages/documentation/docs/controls/breadcrumb.md
  packages/documentation/static/img/pattern_illustrations/Breadcrumb_overview.png
  packages/documentation/static/img/pattern_illustrations/Breadcrumb_variants.png
Labels: component: documentation

#425 fix(core/dropdown): allow nested dropdown
  packages/core/component-doc.json
  packages/core/scss/components/_dropdown.scss
  packages/core/src/components.d.ts
  packages/core/src/components/divider/divider.scss
  packages/core/src/components/divider/divider.tsx
  packages/core/src/components/dropdown-button/dropdown-button.scss
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/dropdown-item/dropdown-item.scss
  packages/core/src/components/dropdown/dropdown.scss
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/__snapshots__/dropdown.spec.tsx.snap
  packages/core/src/components/dropdown/test/dropdown.spec.tsx
  packages/core/src/components/tree/tree.tsx
  packages/core/src/tests/dropdown-quick-actions/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/dropdown-quick-actions/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#430 fix(core/tree): set toggle listener when has children changes
  packages/core/src/components/tree/tree.tsx
Labels: semvers: patch

#428 fix(core/dropdown): remove button overwrite
  packages/core/scss/components/_dropdown.scss
Labels: semvers: patch

#431 chore: update stencil to v3.0.0
  packages/aggrid/package.json
  packages/aggrid/src/components.d.ts
  packages/angular/src/angular-component-lib/utils.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/.eslintrc.json
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/button/button-variants.ts
  packages/core/src/components/button/button.tsx
  packages/core/src/components/date-picker/date-picker.tsx
  packages/core/src/components/date-picker/events.ts
  packages/core/src/components/date-time-card/date-time-card.tsx
  packages/core/src/components/datetime-picker/datetime-picker.tsx
  packages/core/src/components/datetime-picker/event.ts
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/dropdown/dropdown-trigger-event.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/icon-button/icon-button.tsx
  packages/core/src/components/modal-container/modal-container.tsx
  packages/core/src/components/modal/modal-utils.ts
  packages/core/src/components/split-button/split-button.tsx
  packages/core/src/components/time-picker/time-picker.tsx
  packages/core/src/components/utils/typed-event.ts
  packages/core/src/env.ts
  packages/core/src/exports.ts
  packages/core/src/index.ts
  packages/react/src/components.ts
  packages/react/src/react-component-lib/createComponent.tsx
  packages/react/src/react-component-lib/createOverlayComponent.tsx
  packages/react/src/react-component-lib/utils/case.ts
  packages/react/src/react-component-lib/utils/index.tsx
  yarn.lock
Labels: semvers: patch

#435 fix(core/dropdown): fix editable dropdown width
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/select/editable/index.html
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-editable-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-editable-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#420 fix(core/menu-item): adjust bottom background color
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#413 feat(core/pagination): add pagination component
  packages/angular-test-app/src/preview-examples/pagination-advanced.ts
  packages/angular-test-app/src/preview-examples/pagination.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/scss/components/_forms.scss
  packages/core/src/components.d.ts
  packages/core/src/components/category-filter/category-filter.tsx
  packages/core/src/components/index-button/index-button.scss
  packages/core/src/components/index-button/index-button.tsx
  packages/core/src/components/pagination/pagination.scss
  packages/core/src/components/pagination/pagination.tsx
  packages/core/src/components/pagination/test/pagination.spec.tsx
  packages/core/src/tests/pagination/advanced/index.html
  packages/core/src/tests/pagination/basic/index.html
  packages/core/src/tests/pagination/pagination.e2e.ts
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/pagination.md
  packages/documentation/docs/controls/spinner.md
  packages/html-test-app/src/preview-examples/pagination-advanced.html
  packages/html-test-app/src/preview-examples/pagination.html
  packages/react-test-app/src/preview-examples/pagination-advanced.tsx
  packages/react-test-app/src/preview-examples/pagination.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/preview-examples/pagination-advanced.vue
  packages/vue-test-app/src/preview-examples/pagination.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#446 fix(core/select): stop form trigger
  packages/core/src/components/dropdown-item/dropdown-item.tsx
Labels: semvers: patch

#427 feat(core/flip-tile): add support for custom sizing
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/flip-tile/flip-tile.scss
  packages/core/src/components/flip-tile/flip-tile.tsx
  packages/core/src/tests/flip-tile/custom-sizes/index.html
  packages/core/src/tests/flip-tile/flip-tile.e2e.ts
  packages/core/src/tests/flip-tile/flip-tile.e2e.ts-snapshots/flip-tile-custom-sizes-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/flip-tile/flip-tile.e2e.ts-snapshots/flip-tile-custom-sizes-1-chromium---theme-classic-light-linux.png
  packages/vue/src/components.ts
Labels: semvers: minor

#438 feat(core/tree): add node clicked and toggled events
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/tree/tree.tsx
  packages/vue/src/components.ts
Labels: semvers: minor

#432 feat(core/toast): add position top-right
  packages/angular-test-app/src/preview-examples/toast-position.ts
  packages/angular/src/toast/toast.service.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/toast/styles/toast-container.scss
  packages/core/src/components/toast/toast-container.tsx
  packages/core/src/components/toast/toast-utils.ts
  packages/core/src/tests/toast/position/index.html
  packages/core/src/tests/toast/toast.e2e.ts
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-position-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-position-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/toast.md
  packages/html-test-app/src/preview-examples/toast-position.html
  packages/react-test-app/src/preview-examples/toast-position.tsx
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/toast-position.vue
  packages/vue/src/toast/toast.ts
Labels: semvers: minor

#426 fix(core/workflow-step): icons overflow
  packages/core/src/components/workflow-step/workflow-step.scss
  packages/core/src/tests/workflow-steps/overflow/index.html
  packages/core/src/tests/workflow-steps/workflow-steps.e2e.ts
  packages/core/src/tests/workflow-steps/workflow-steps.e2e.ts-snapshots/workflow-steps-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/workflow-steps/workflow-steps.e2e.ts-snapshots/workflow-steps-overflow-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#448 feat(core/blind): add icon and actions slot
  packages/angular-test-app/src/preview-examples/blind-header-actions.ts
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/tests/blind/blind.e2e.ts
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/header-actions/index.html
  packages/documentation/docs/controls/_blind_code.md
  packages/html-test-app/src/preview-examples/blind-header-actions.html
  packages/react-test-app/src/preview-examples/blind-header-actions.tsx
  packages/vue-test-app/src/preview-examples/blind-header-actions.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#451 fix(core/tooltip): remove arrow if not visible
  packages/core/src/components/tooltip/tooltip.scss
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/src/tests/tooltip/placement-fallback/index.html
  packages/core/src/tests/tooltip/tooltip.e2e.ts
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-fallback-placement-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-fallback-placement-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#447 docs(button): update button description
  packages/documentation/docs/controls/_button_code.md
  packages/documentation/docs/controls/_button_styleguide.md
  packages/documentation/docs/controls/button.md
  packages/documentation/static/img/pattern_illustrations/button_group.png
  packages/documentation/static/img/pattern_illustrations/button_overview.png
  packages/documentation/static/img/pattern_illustrations/button_states.png
Labels: component: documentation

#457 chore: update yarn.lock to latest ix-icons version
  yarn.lock
Labels: semvers: patch

#462 docs(security): add securty page with csp section
  packages/documentation/docs/installation/javascript.md
  packages/documentation/docs/installation/security.md
  packages/documentation/docs/installation/vue.md
Labels: component: documentation

#453 fix(core/group): header and item hover/active style
  packages/core/src/components/group-item/group-item.scss
  packages/core/src/components/group/group.scss
  packages/core/src/tests/group/basic/index.html
  packages/core/src/tests/group/group.e2e.ts
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-selected-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-selected-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#466 feat(core/tooltip): add position property
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/src/tests/tooltip/tooltip.e2e.ts
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-bottom-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-bottom-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-left-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-left-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-right-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-right-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-top-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/tooltip/tooltip.e2e.ts-snapshots/tooltip-tooltip-position-top-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/utils/ct/index.html
  packages/core/src/tests/utils/test/page.ts
  packages/vue/src/components.ts
Labels: semvers: minor

#465 fix(core/select): clear button
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/select/allow-clear/index.html
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-allow-clear-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-allow-clear-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#469 fix(core/modal): close only target modal
  packages/core/src/components/modal-container/modal-container.tsx
  packages/core/src/components/modal-container/test/modal-container.spec.tsx
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/test/__snapshots__/modal.spec.tsx.snap
  packages/react/src/modal/index.ts
  packages/react/src/modal/modal.tsx
Labels: semvers: patch

#473 feat(core/datepicker): improve useability of the datepicker for range selection
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/date-picker/date-picker.tsx
  packages/core/src/components/date-picker/test/date-picker.spec.tsx
Labels: semvers: minor

#461 fix(core/blind): improve keyboard accessibility
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch
