Repository siemens/ix, pull requests merged in 2023-02, with the labels that each got.

#334 fix(core/date-picker): handle empty from date
  packages/core/src/components/date-picker/date-picker.tsx
Labels: semvers: patch

#339 fix(core/split-button): dropdown behavior and middle space
  packages/core/src/components/split-button/split-button.scss
  packages/core/src/components/split-button/split-button.tsx
Labels: semvers: patch

#335 fix(core/event-list): hover on selected and transition effect
  packages/core/src/components/event-list-item/event-list-item.scss
Labels: semvers: patch

#364 fix(core/button): button sizing behavior
  packages/core/playwright.config.ts
  packages/core/src/components/button/button.scss
  packages/core/src/components/button/button.tsx
  packages/core/src/components/button/test/button.spec.tsx
  packages/core/src/components/dropdown-button/dropdown-button.scss
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/split-button/split-button.scss
  packages/core/src/components/tooltip/test/tooltip.e2e.ts
  packages/core/src/components/tooltip/test/tooltip.e2e.ts-snapshots/tooltip-Short-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/tooltip/test/tooltip.e2e.ts-snapshots/tooltip-Short-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#365 docs(design-kit): figma siemens section
  packages/documentation/docs/design-kit/design-kit.md
Labels: component: core

#356 fix(core/toggle): toggle disable style
  packages/core/scss/theme/classic-dark/_borderWidth.scss
  packages/core/scss/theme/classic-dark/_color.scss
  packages/core/scss/theme/classic-light/_borderWidth.scss
  packages/core/scss/theme/classic-light/_color.scss
  packages/core/src/components/toggle/test/disabled/index.html
  packages/core/src/components/toggle/test/toggle.e2e.ts
  packages/core/src/components/toggle/test/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/toggle/test/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/toggle/test/toggle.spec.ts
  packages/core/src/components/toggle/toggle.scss
Labels: type: bug, component: core

#367 docs(modal): add framework specific apis
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/modal-by-instance-content.ts
  packages/angular-test-app/src/preview-examples/modal-by-instance.ts
  packages/documentation/docs/controls/_modal/angular/modal-config.md
  packages/documentation/docs/controls/_modal/angular/modal-instance.html.md
  packages/documentation/docs/controls/_modal/angular/modal-service.html.md
  packages/documentation/docs/controls/_modal/react/modal-config.md
  packages/documentation/docs/controls/_modal/react/modal-ref.html.md
  packages/documentation/docs/controls/modal.md
Labels: component: documentation

#323 docs(blind): add ux description
  packages/documentation/docs/controls/_blind_code.md
  packages/documentation/docs/controls/_blind_styleguide.md
  packages/documentation/docs/controls/blind.md
  packages/documentation/src/components/DocsTabs/DocsTabs.scss
  packages/documentation/src/components/DocsTabs/index.tsx
  packages/documentation/src/css/custom.css
  packages/documentation/static/img/pattern_illustrations/Blind_accordion.png
  packages/documentation/static/img/pattern_illustrations/Blind_overview.png
  packages/documentation/static/img/pattern_illustrations/Blind_states1.png
  packages/documentation/static/img/pattern_illustrations/Blind_states2.png
Labels: component: documentation, triage

#376 fix(core/toast): delay animation into next frame
  packages/core/src/components/toast/toast.tsx
Labels: semvers: patch

#378 fix(aggrid): convert px to rem
  packages/aggrid/scss/ix-aggrid.scss
Labels: semvers: patch

#379 fix(core/menu): use scoped context in menu item
  packages/core/component-doc.json
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/components/menu-item/menu-item.tsx
  packages/core/src/components/menu/menu.tsx
Labels: semvers: patch

#383 fix(core/form-validation): form-validation invalid correction
  packages/core/scss/components/_forms.scss
Labels: semvers: patch

#375 feat(core/avatar): initals and image support
  packages/angular-test-app/src/preview-examples/vertical-tabs-with-avatar.ts
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/menu-avatar/menu-avatar.scss
  packages/core/src/components/menu-avatar/menu-avatar.tsx
  packages/core/src/components/menu-avatar/test/image/index.html
  packages/core/src/components/menu-avatar/test/image/jd.png
  packages/core/src/components/menu-avatar/test/initials/index.html
  packages/core/src/components/menu-avatar/test/initials/jd.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
  packages/html-test-app/src/preview-examples/menu-with-bottom-tabs.html
  packages/html-test-app/src/preview-examples/vertical-tabs-with-avatar.html
  packages/html-test-app/src/preview-examples/vertical-tabs.html
  packages/react-test-app/src/preview-examples/menu-with-bottom-tabs.tsx
  packages/react-test-app/src/preview-examples/vertical-tabs-with-avatar.tsx
  packages/react-test-app/src/preview-examples/vertical-tabs.tsx
Labels: semvers: minor

#380 feat(core/basic-navigation): add mobile support
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/application-header/application-header.scss
  packages/core/src/components/application-header/application-header.tsx
  packages/core/src/components/application-header/test/cw-application-header.spec.tsx
  packages/core/src/components/basic-navigation/basic-navigation.scss
  packages/core/src/components/basic-navigation/basic-navigation.tsx
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-overlay-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/basic-navigation/test/mobile/index.html
  packages/core/src/components/button/button-variants.ts
  packages/core/src/components/button/button.tsx
  packages/core/src/components/dropdown-button/dropdown-button.tsx
  packages/core/src/components/map-navigation/test/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/map-navigation/test/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-about-news/test/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-about-news/test/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-about/test/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-about/test/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-settings/test/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-settings/test/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu/burger-menu.scss
  packages/core/src/components/menu/burger-menu.tsx
  packages/core/src/components/menu/menu.scss
  packages/core/src/components/menu/menu.tsx
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/components/split-button/split-button.tsx
  packages/core/src/components/utils/menu-service/menu-service.ts
  packages/core/src/components/utils/screen/context.ts
  packages/core/src/components/utils/screen/index.ts
  packages/core/src/components/utils/screen/mode.ts
  packages/core/src/components/utils/screen/service.ts
  packages/core/src/components/utils/tests/rwd.util.spec.ts
  packages/core/src/components/utils/tests/theme-switcher.e2e.ts
  packages/core/src/index.html
  packages/core/src/index.ts
  packages/core/src/utils/test/matchMedia.mock.js
  packages/core/stencil.config.ts
Labels: semvers: minor

#377 docs(html-examples): use custom properties in placeholder logo
  packages/html-test-app/src/main.js
  packages/html-test-app/src/preview-examples/about-and-legal.html
  packages/html-test-app/src/preview-examples/basic-navigation.html
  packages/html-test-app/src/preview-examples/init.js
  packages/html-test-app/src/preview-examples/map-navigation-overlay.html
  packages/html-test-app/src/preview-examples/map-navigation.html
  packages/html-test-app/src/preview-examples/placeholder-logo.css
  packages/html-test-app/src/preview-examples/placeholder-logo.js
  packages/html-test-app/src/preview-examples/popover-news.html
  packages/html-test-app/src/preview-examples/settings.html
Labels: component: documentation

#325 feat(core/dropdown): submenu and quickactions
  packages/angular-test-app/src/preview-examples/divider.ts
  packages/angular-test-app/src/preview-examples/dropdown-quick-actions.html
  packages/angular-test-app/src/preview-examples/dropdown-quick-actions.ts
  packages/angular-test-app/src/preview-examples/dropdown-submenu.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/breadcrumb/test/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/breadcrumb/test/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-dark-win32.png
  packages/core/src/components/breadcrumb/test/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/breadcrumb/test/breadcrumb.e2e.ts-snapshots/breadcrumb-lazyLoaded-1-chromium---theme-classic-light-win32.png
  packages/core/src/components/category-filter/category-filter.tsx
  packages/core/src/components/divider/divider.scss
  packages/core/src/components/divider/divider.tsx
  packages/core/src/components/divider/test/basic/index.html
  packages/core/src/components/divider/test/divider.e2e.ts
  packages/core/src/components/divider/test/divider.e2e.ts-snapshots/divider-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/divider/test/divider.e2e.ts-snapshots/divider-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/dropdown-button/test/dropdown-button.e2e.ts-snapshots/basic-dropdown-should-open-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/dropdown-button/test/dropdown-button.e2e.ts-snapshots/basic-dropdown-should-open-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/dropdown-item/dropdown-item.scss
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/core/src/components/dropdown-quick-actions/dropdown-quick-actions.scss
  packages/core/src/components/dropdown-quick-actions/dropdown-quick-actions.tsx
  packages/core/src/components/dropdown-quick-actions/test/basic/index.html
  packages/core/src/components/dropdown-quick-actions/test/dropdown-quick-actions.e2e.ts
  packages/core/src/components/dropdown-quick-actions/test/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/dropdown-quick-actions/test/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/dropdown/dropdown-trigger-event.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.e2e.ts
  packages/core/src/components/dropdown/test/dropdown.e2e.ts-snapshots/dropdown-tigger-events-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/dropdown/test/dropdown.e2e.ts-snapshots/dropdown-tigger-events-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/dropdown/test/trigger-events/index.html
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/menu-avatar/test/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
  packages/core/src/exports.ts
  packages/core/src/index.ts
  packages/documentation/docs/controls/divider.md
  packages/documentation/docs/controls/dropdown.md
  packages/html-test-app/src/preview-examples/divider.html
  packages/html-test-app/src/preview-examples/dropdown-quick-actions.html
  packages/html-test-app/src/preview-examples/dropdown-submenu.html
  packages/react-test-app/src/preview-examples/divider.tsx
  packages/react-test-app/src/preview-examples/dropdown-quick-actions.tsx
  packages/react-test-app/src/preview-examples/dropdown-submenu.tsx
  packages/react/src/components.ts
Labels: semvers: minor

#389 docs(dropdown): fix import path
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/basic-navigation/test/basic-navigation.e2e.ts-snapshots/basic-navigation-mobile-mobile-expanded-overlay-1-chromium---theme-classic-light-linux.png
  packages/core/src/components/dropdown-quick-actions/test/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/components/dropdown-quick-actions/test/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/dropdown.md
Labels: component: documentation

#390 fix(core/dropdown-item): dropdown item disabled state events & icon color
  packages/core/scss/components/_dropdown.scss
  packages/core/src/components/dropdown-item/dropdown-item.scss
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/tests/dropdown/disabled/index.html
  packages/core/src/tests/dropdown/dropdown.e2e.ts
  packages/core/src/tests/dropdown/dropdown.e2e.ts-snapshots/dropdown-disabled-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/dropdown/dropdown.e2e.ts-snapshots/dropdown-disabled-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#398 fix(core/select): adjust dropdown placement
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/my-component/my-component.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/select/autoplacement/index.html
  packages/core/src/tests/select/overflow/index.html
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#411 feat(core/menu): replace burger menu animation
  packages/core/src/components/menu/burger-menu.scss
  packages/core/src/components/menu/burger-menu.tsx
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#406 docs: refactor styling
  packages/angular-test-app/src/preview-examples/dropdown-quick-actions.html
  packages/angular-test-app/src/preview-examples/validation.ts
  packages/core/component-doc.json
  packages/core/scss/components/_forms.scss
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/toast/styles/toast-container.scss
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/src/tests/dropdown/disabled/index.html
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toast/toast.e2e.ts-snapshots/toast-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/dropdown.md
  packages/documentation/docs/theming/animation.md
  packages/documentation/docs/theming/borders.md
  packages/documentation/docs/theming/colors.md
  packages/documentation/docs/theming/fonts.md
  packages/documentation/docs/theming/shadow.md
  packages/documentation/src/components/ThemeBorders/ThemeBorders.css
  packages/documentation/src/components/ThemeBorders/borders.ts
  packages/documentation/src/components/ThemeBorders/index.tsx
  packages/documentation/src/components/ThemeColors/ThemeColors.css
  packages/documentation/src/components/ThemeColors/index.tsx
  packages/documentation/src/components/ThemeColors/resolve-colors.ts
  packages/documentation/src/components/ThemeFonts/ThemeFonts.css
  packages/documentation/src/components/ThemeFonts/fonts.ts
  packages/documentation/src/components/ThemeFonts/index.tsx
  packages/documentation/src/components/ThemeShadows/ThemeShadows.css
  packages/documentation/src/components/ThemeShadows/index.tsx
  packages/documentation/src/components/ThemeShadows/shadows.ts
  packages/documentation/src/components/pages/HomepageFeatures.tsx
  packages/documentation/src/css/custom.css
  packages/documentation/static/img/transparency500.png
  packages/html-test-app/src/preview-examples/dropdown-quick-actions.html
  packages/html-test-app/src/preview-examples/validation.html
  packages/react-test-app/src/preview-examples/dropdown-quick-actions.tsx
  packages/react-test-app/src/preview-examples/validation.tsx
Labels: semvers: patch
