Repository siemens/ix, pull requests merged in 2023-10, with the labels that each got.

#788 fix(core/modal): skip tick during vdom rendering
  packages/core/src/components/modal/modal.tsx
Labels: semvers: patch

#789 fix(core/drodown): nested dropdown closes parent dropdown
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.ct.ts
Labels: semvers: patch

#804 fix(core/button): prevent native events to be dispatched
  packages/core/src/components/button/button-mixin.scss
  packages/core/src/components/button/test/button.ct.ts
Labels: semvers: patch

#806 fix(react/tree): load ix-tree web component on initialize react lib
  packages/react/src/tree/tree.tsx
Labels: semvers: patch

#803 fix(core/input-group): detect inital value padding
  packages/core/src/components/input-group/input-group.tsx
  packages/core/src/components/input-group/tests/input-group.ct.ts
Labels: semvers: patch

#811 fix(core/breadcrumb): check if overflow button is existing in DOM
  packages/core/src/components/breadcrumb-item/breadcrumb-item.tsx
  packages/core/src/components/breadcrumb/breadcrumb.tsx
  packages/core/src/components/utils/a11y.ts
Labels: semvers: patch

#815 fix(core/drawer): add missing host class selector
  packages/core/src/components/drawer/drawer.scss
Labels: semvers: patch

#816 fix(core/checkbox, core/radiobutton): remove min-height
  packages/core/scss/components/_checkboxes.scss
  packages/core/scss/components/_radiobuttons.scss
Labels: semvers: patch

#836 fix(core/modal): use percentage to align modal centered
  packages/core/src/components/modal/modal.tsx
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts
  packages/core/src/tests/modal/modal.e2e.ts
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-should-show-centered-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-should-show-centered-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#839 fix(core/button): prevent interaction of ix-icon
  packages/core/src/components/button/base-button.tsx
  packages/core/src/components/button/button-mixin.scss
Labels: semvers: patch

#844 docs(blazor): upate info box
  packages/documentation/docs/installation/blazor.md
Labels: component: documentation

#845 docs: website improvements
  packages/documentation/docusaurus.config.js
  packages/documentation/src/components/Card.module.css
  packages/documentation/src/components/Card.tsx
  packages/documentation/src/css/api-table.scss
  packages/documentation/src/css/cards.scss
  packages/documentation/src/css/custom.scss
  packages/documentation/src/css/search.scss
  packages/documentation/src/theme/Navbar/Logo/index.js
Labels: component: documentation

#855 fix(core): request animation depending on zonejs; reduce global events
  packages/core/component-doc.json
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/select/select.tsx
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/tabs/tabs.tsx
  packages/core/src/components/utils/listener.ts
  packages/core/src/components/utils/requestAnimationFrame.ts
Labels: semvers: patch

#867 fix(core/tree): add undefined check to disconnected callback
  packages/core/src/components/tree/tree.tsx
Labels: type: bug

#864 build(aggrid): remove stencil dependency
  packages/aggrid/README.md
  packages/aggrid/gulpfile.ts
  packages/aggrid/package.json
  packages/aggrid/scss/ix-aggrid.scss
  packages/aggrid/src/components.d.ts
  packages/aggrid/src/components/ix-ag-grid/ix-ag-grid.tsx
  packages/aggrid/src/components/my-component/my-component.scss
  packages/aggrid/src/components/my-component/my-component.tsx
  packages/aggrid/src/index.html
  packages/aggrid/src/index.ts
  packages/aggrid/stencil.config.ts
  packages/aggrid/tests/aggrid.e2e.ts
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-basic-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-basic-1-chromium---theme-classic-light-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-editor-1-chromium---theme-classic-light-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-filter-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-filter-1-chromium---theme-classic-light-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-pagination-1-chromium---theme-classic-dark-linux.png
  packages/aggrid/tests/aggrid.e2e.ts-snapshots/aggrid-pagination-1-chromium---theme-classic-light-linux.png
  packages/aggrid/tests/basic.html
  packages/aggrid/tests/pagination.html
  packages/aggrid/tests/utils/test/index.ts
  packages/aggrid/tests/utils/test/page.ts
  packages/aggrid/tests/utils/test/theme-switcher.js
  packages/aggrid/tsconfig.base.json
  packages/aggrid/tsconfig.json
  yarn.lock
Labels: semvers: patch

#868 docs: adapt links; add chart colors; rename tiles
  packages/documentation/docs/getting-started-for-designers.md
  packages/documentation/docs/getting-started.md
  packages/documentation/docs/guidelines/theme.md
  packages/documentation/src/components/ThemeColors/resolve-colors.ts
Labels: component: documentation

#871 fix(core/typography): use ms--1 size in h6
  packages/core/scss/mixins/_fonts.scss
  packages/core/src/tests/fonts/fonts.e2e.ts-snapshots/fonts-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/fonts/fonts.e2e.ts-snapshots/fonts-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#874 fix(core/basic-navigation): fixed behavior on missing breakpoints
  packages/core/src/components/utils/application-layout/service.ts
Labels: semvers: patch

#859 fix(core/event-list-item): fix right padding
  packages/core/src/components/event-list-item/event-list-item.scss
  packages/core/src/tests/event-list/chevron/index.html
Labels: semvers: patch

#784 fix(core/select): filter corrections
  packages/core/src/components/select/select.tsx
  packages/core/src/components/select/test/select.ct.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch
