Repository siemens/ix, pull requests merged in 2023-04, with the labels that each got.

#471 feat(core/select): hide header text
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/select/select.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/select/list-header-hide/index.html
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-list-header-hide-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-list-header-hide-1-chromium---theme-classic-light-linux.png
  packages/vue/src/components.ts
Labels: semvers: minor

#474 fix(core/select): add vertical margin to filter chips
  package.json
  packages/aggrid/package.json
  packages/core/package.json
  packages/core/src/components/select/select.scss
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-light-linux.png
  yarn.lock
Labels: semvers: patch

#478 fix(core/toggle): remove attribute selector for disable state
  packages/core/src/components/toggle/toggle.scss
Labels: semvers: patch

#485 fix(core/form-controls): Input, Select, Textarea readonly states
  packages/core/scss/components/_forms.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/input/input.e2e.ts
  packages/core/src/tests/input/input.e2e.ts-snapshots/input-readonly-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/input/input.e2e.ts-snapshots/input-readonly-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/input/readonly/index.html
  packages/core/src/tests/select/readonly/index.html
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/textarea/basic/index.html
  packages/core/src/tests/textarea/readonly/index.html
  packages/core/src/tests/textarea/textarea.e2e.ts
  packages/core/src/tests/textarea/textarea.e2e.ts-snapshots/textarea-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/textarea/textarea.e2e.ts-snapshots/textarea-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/textarea/textarea.e2e.ts-snapshots/textarea-readonly-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/textarea/textarea.e2e.ts-snapshots/textarea-readonly-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#470 fix(core/group): group selected style and actions & header correction
  packages/core/component-doc.json
  packages/core/src/components/group-item/group-item.scss
  packages/core/src/components/group/group.scss
  packages/core/src/components/group/group.tsx
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/tests/group/group.e2e.ts
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-selected-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-selected-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#479 fix(core/category-filter): options
  packages/core/src/components/category-filter/category-filter.tsx
Labels: semvers: patch

#489 feat(core/select): show info if no matches found and fix selection bug
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown-item/dropdown-item.scss
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/pagination/pagination.tsx
  packages/core/src/components/select-item/select-item.scss
  packages/core/src/components/select-item/select-item.tsx
  packages/core/src/components/select/select.tsx
  packages/core/src/tests/dropdown-button/dropdown-button.e2e.ts
  packages/vue/src/components.ts
Labels: semvers: minor

#490 fix(core): Inputs and Textareas cursor
  packages/core/scss/components/_forms.scss
Labels: semvers: patch

#496 docs: restructure navigation layout
  packages/documentation/docs/controls/_breadcrumb_styleguide.md
  packages/documentation/docs/controls/_button_styleguide.md
  packages/documentation/docs/design-kit/design-kit.md
  packages/documentation/docs/getting-started-for-designers.md
  packages/documentation/docs/getting-started.md
  packages/documentation/docs/guidelines/theme.md
  packages/documentation/docs/installation/blazor.md
  packages/documentation/docs/installation/installation.md
  packages/documentation/docs/introduction.md
  packages/documentation/docs/migration/_category_.json
  packages/documentation/docs/migration/core-ui.md
  packages/documentation/docs/team.md
  packages/documentation/docs/theming/theming-and-styling.md
  packages/documentation/docusaurus.config.js
  packages/documentation/package.json
  packages/documentation/scripts/tsconfig.json
  packages/documentation/sidebars.js
  packages/documentation/src/components/Card.tsx
  packages/documentation/src/components/Color.tsx
  packages/documentation/src/components/DocsComponents/GuidingPrinciples/GuidingPrincipleCard.scss
  packages/documentation/src/components/DocsComponents/GuidingPrinciples/GuidingPrinciples.scss
  packages/documentation/src/components/DocsComponents/GuidingPrinciples/index.tsx
  packages/documentation/src/components/Fonts.tsx
  packages/documentation/src/components/Icons.tsx
  packages/documentation/src/css/custom.css
  packages/documentation/static/img/blazor.svg
  yarn.lock
Labels: component: documentation

#497 chore: update to @stencil/core 3.2.1
  packages/aggrid/package.json
  packages/core/component-doc.json
  packages/core/package.json
  yarn.lock
Labels: semvers: minor
