Repository siemens/ix, pull requests merged in 2023-11, with the labels that each got.

#849 fix(core/ix-dropdown): reworked nested dropdown fix
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.spec.tsx
Labels: semvers: patch

#876 fix(core/blind): remove custom action from button tag
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/components/blind/test/blind.ct.ts
  packages/core/src/tests/blind/blind.e2e.ts
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-header-actions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-should-no-hover-on-slot-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-should-no-hover-on-slot-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#906 chore: bump ix version to 2.0.4-beta.0
  CHANGELOG.md
  package.json
  packages/aggrid/package.json
  packages/angular-test-app/package.json
  packages/angular/package.json
  packages/core/package.json
  packages/documentation/docs/installation/CHANGELOG.md
  packages/documentation/package.json
  packages/echarts/package.json
  packages/html-test-app/package.json
  packages/react-test-app/package.json
  packages/react/package.json
  packages/vue-test-app/package.json
  packages/vue/package.json
Labels: semvers: patch

#910 docs(figma-plugin): optimize image fetching
  packages/documentation/docusaurus.config.js
  packages/figma-plugin/figma.js
  packages/figma-plugin/index.js
  packages/figma-plugin/package.json
  packages/figma-plugin/src/figma.ts
  packages/figma-plugin/tsconfig.json
  yarn.lock
Labels: component: documentation

#870 fix(core/modal): ensure that key down listener gets called
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/modal/modal.tsx
  packages/core/src/components/modal/test/modal.ct.ts
  packages/vue/src/components.ts
Labels: semvers: minor

#797 feat(core/date-dropdown): new date-dropdown component
  package-lock.json
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/date-dropdown-user-range.ts
  packages/angular-test-app/src/preview-examples/date-dropdown.ts
  packages/angular-test-app/tsconfig.json
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/date-dropdown/date-dropdown.scss
  packages/core/src/components/date-dropdown/date-dropdown.tsx
  packages/core/src/components/date-dropdown/test/date-dropdown.ct.ts
  packages/core/src/index.html
  packages/core/src/tests/date-dropdown/basic/index.html
  packages/core/src/tests/date-dropdown/date-dropdown.e2e.ts
  packages/core/src/tests/date-dropdown/date-dropdown.e2e.ts-snapshots/date-dropdown-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/date-dropdown/date-dropdown.e2e.ts-snapshots/date-dropdown-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/date-dropdown.md
  packages/html-test-app/src/preview-examples/date-dropdown-user-range.html
  packages/html-test-app/src/preview-examples/date-dropdown.html
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/date-dropdown-user-range.tsx
  packages/react-test-app/src/preview-examples/date-dropdown.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/date-dropdown-user-range.vue
  packages/vue-test-app/src/preview-examples/date-dropdown.vue
  packages/vue/src/components.ts
  yarn.lock
Labels: semvers: minor

#851 feat(core/menu-avatar): optional logout button, conditional dropdown
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/menu-avatar/menu-avatar.tsx
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-no-dropdown-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-no-dropdown-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/no-dropdown/index.html
  packages/vue/src/components.ts
Labels: semvers: minor

#502 feat(core/icon-button): implement a11y features for icon-button
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/icon-button/icon-button.tsx
  packages/core/src/components/icon-button/test/icon-button.spec.ts
  packages/core/src/components/utils/a11y.ts
  packages/core/src/components/utils/condition-checks.ts
  packages/vue/src/components.ts
Labels: semvers: patch

#889 doc(core/basic-navigation): documentation fix
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/basic-navigation/basic-navigation.tsx
Labels: semvers: patch

#928 docs(core/card|card-list): add style guide and update examples
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/card.html
  packages/angular-test-app/src/preview-examples/card.ts
  packages/documentation/docs/controls/_card-list_code.md
  packages/documentation/docs/controls/_card-list_styleguide.md
  packages/documentation/docs/controls/_card_code.md
  packages/documentation/docs/controls/_card_styleguide.md
  packages/documentation/docs/controls/card-list.md
  packages/documentation/docs/controls/card.md
  packages/html-test-app/src/preview-examples/card.html
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/card.tsx
  packages/react-test-app/src/preview-examples/styles/card.css
  packages/vue-test-app/src/preview-examples/card.vue
Labels: semvers: patch

#556 fix(core/tooltip): accessibility
  packages/core/src/components/tooltip/test/tooltip.ct.ts
  packages/core/src/components/tooltip/tooltip.tsx
Labels: semvers: patch

#887 fix(core/menu-item): suppress icon tooltip
  packages/core/src/components/menu-item/menu-item.scss
Labels: semvers: patch

#904 docs: chip styleguide
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/chip/chip.tsx
  packages/documentation/docs/controls/_chip_code.md
  packages/documentation/docs/controls/_chip_styleguide.md
  packages/documentation/docs/controls/chip.md
Labels: semvers: patch

#941 fix(core/burger-menu): cursor appearance
  packages/core/src/components/menu/burger-menu.scss
Labels: semvers: patch
