Repository siemens/ix, pull requests merged in 2023-05, with the labels that each got.

#512 fix(core/time-picker): make inputs editable
  packages/core/component-doc.json
  packages/core/src/components/time-picker/time-picker.scss
  packages/core/src/components/time-picker/time-picker.tsx
  packages/core/src/tests/datetime-picker/datetime-picker.e2e.ts-snapshots/datetime-picker-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/datetime-picker/datetime-picker.e2e.ts-snapshots/datetime-picker-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/time-picker/basic/index.html
  packages/core/src/tests/time-picker/time-picker.e2e.ts-snapshots/time-picker-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/time-picker/time-picker.e2e.ts-snapshots/time-picker-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#517 fix(core/modal): border-radius value
  packages/core/src/components/modal/modal.scss
Labels: semvers: patch

#527 fix(core/menu): menu more disabled state
  packages/core/src/components/menu/menu.tsx
Labels: semvers: patch

#530 feat(core/typography): add color property
  packages/core/src/components.d.ts
  packages/core/src/components/typography/test/ix-typography.spec.tsx
  packages/core/src/components/typography/types.ts
  packages/core/src/components/typography/typography.tsx
Labels: semvers: minor

#524 feat(core): integrate @siemens/ix-icons web components
  .gitignore
  packages/angular-test-app/package.json
  packages/angular/package.json
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/icon/icon.scss
  packages/core/src/components/icon/icon.tsx
  packages/core/src/components/icon/test/cw-icon.spec.tsx
  packages/core/src/components/my-component/my-component.tsx
  packages/core/src/index.ts
  packages/documentation/package.json
  packages/documentation/src/components/Card.module.css
  packages/documentation/src/components/Card.tsx
  packages/documentation/src/css/custom.css
  packages/html-test-app/package.json
  packages/react-test-app/package.json
  packages/react/package.json
  packages/vue-test-app/package.json
  packages/vue/package.json
  packages/vue/src/components.ts
  yarn.lock
Labels: semvers: minor

#523 feat(core/empty-state): implement empty state
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/empty-state-compact-break.ts
  packages/angular-test-app/src/preview-examples/empty-state-compact.ts
  packages/angular-test-app/src/preview-examples/empty-state.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/empty-state/empty-state.scss
  packages/core/src/components/empty-state/empty-state.tsx
  packages/core/src/tests/empty-state/basic/index.html
  packages/core/src/tests/empty-state/compact-break/index.html
  packages/core/src/tests/empty-state/compact/index.html
  packages/core/src/tests/empty-state/empty-state.e2e.ts
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-compact-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-compact-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-compact-break-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/empty-state/empty-state.e2e.ts-snapshots/empty-state-compact-break-1-chromium---theme-classic-light-linux.png
  packages/core/stencil.config.ts
  packages/documentation/docs/controls/empty-state.md
  packages/documentation/scripts/generate-api.ts
  packages/html-test-app/src/preview-examples/empty-state-compact-break.html
  packages/html-test-app/src/preview-examples/empty-state-compact.html
  packages/html-test-app/src/preview-examples/empty-state.html
  packages/react-test-app/src/preview-examples/empty-state-compact-break.tsx
  packages/react-test-app/src/preview-examples/empty-state-compact.tsx
  packages/react-test-app/src/preview-examples/empty-state.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/empty-state-compact-break.vue
  packages/vue-test-app/src/preview-examples/empty-state-compact.vue
  packages/vue-test-app/src/preview-examples/empty-state.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#533 feat(core/bind): enable shadowDOM
  packages/core/component-doc.json
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/tests/blind/blind.e2e.ts
Labels: semvers: patch

#514 fix(core/menu): adapt width
  packages/core/src/components/basic-navigation/basic-navigation.scss
  packages/core/src/components/map-navigation/map-navigation.scss
  packages/core/src/components/menu-about-news/menu-about-news.scss
  packages/core/src/components/menu-avatar/menu-avatar.scss
  packages/core/src/components/menu-avatar/menu-avatar.tsx
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/components/menu/menu.scss
  packages/core/src/tests/map-navigation-overlay/map-navigation.e2e.ts-snapshots/map-navigation-overlay-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/map-navigation-overlay/map-navigation.e2e.ts-snapshots/map-navigation-overlay-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-about-news/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-about-news/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#537 fix(core/toast): timer on hover
  packages/core/src/components/toast/toast.scss
  packages/core/src/components/toast/toast.tsx
Labels: semvers: patch

#538 fix(documentation): color preview in production build
  packages/documentation/src/components/Color.tsx
  packages/documentation/src/components/ThemeColors/ThemeColors.css
  packages/documentation/src/components/ThemeColors/index.tsx
  packages/documentation/src/components/transparency500.png
  packages/documentation/static/img/chessboard_pattern.png
  packages/documentation/static/img/transparency500.png
Labels: component: documentation

#526 feat(core/page-header): add page-header
  package.json
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/page-header-no-back.html
  packages/angular-test-app/src/preview-examples/page-header-no-back.ts
  packages/angular-test-app/src/preview-examples/page-header.html
  packages/angular-test-app/src/preview-examples/page-header.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/page-header/page-header.scss
  packages/core/src/components/page-header/page-header.tsx
  packages/core/src/tests/page-header/basic/index.html
  packages/core/src/tests/page-header/page-header.e2e.ts
  packages/core/src/tests/page-header/page-header.e2e.ts-snapshots/page-header-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/page-header/page-header.e2e.ts-snapshots/page-header-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/page-header/page-header.e2e.ts-snapshots/page-header-secondary-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/page-header/page-header.e2e.ts-snapshots/page-header-secondary-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/page-header/secondary/index.html
  packages/core/stencil.config.ts
  packages/documentation/docs/controls/page-header.md
  packages/html-test-app/src/preview-examples/page-header-no-back.html
  packages/html-test-app/src/preview-examples/page-header.html
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/page-header-no-back.tsx
  packages/react-test-app/src/preview-examples/page-header.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/page-header-no-back.vue
  packages/vue-test-app/src/preview-examples/page-header.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#541 fix(docs/homepage): button and arrow no text-decoration
  packages/documentation/src/pages/index.module.scss
Labels: component: documentation

#516 fix(core/select): updated style and multimode functionality
  packages/core/src/components/select/select.scss
  packages/core/src/components/select/select.tsx
  packages/core/src/index.html
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/pagination/pagination.e2e.ts-snapshots/pagination-advanced-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-allow-clear-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-allow-clear-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-autoplacement-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-editable-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-editable-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-list-header-hide-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-list-header-hide-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-mode-multiple-overflow-scroll-down-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-overflow-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/select/select.e2e.ts-snapshots/select-readonly-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#545 feat(core/key-value): implement key value
  package.json
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/breadcrumb-truncate.ts
  packages/angular-test-app/src/preview-examples/key-value-list-striped.ts
  packages/angular-test-app/src/preview-examples/key-value-list-with-custom-value.ts
  packages/angular-test-app/src/preview-examples/key-value-list-with-icon.ts
  packages/angular-test-app/src/preview-examples/key-value-list.ts
  packages/angular-test-app/src/preview-examples/key-value-with-custom-value.ts
  packages/angular-test-app/src/preview-examples/key-value-with-icon.ts
  packages/angular-test-app/src/preview-examples/key-value-with-label-left.ts
  packages/angular-test-app/src/preview-examples/key-value.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components.d.ts
  packages/core/src/components/key-value-list/key-value-list.scss
  packages/core/src/components/key-value-list/key-value-list.tsx
  packages/core/src/components/key-value/key-value.scss
  packages/core/src/components/key-value/key-value.tsx
  packages/core/src/tests/key-value-list/basic/index.html
  packages/core/src/tests/key-value-list/key-value-list.e2e.ts
  packages/core/src/tests/key-value-list/key-value-list.e2e.ts-snapshots/key-value-list-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/key-value-list/key-value-list.e2e.ts-snapshots/key-value-list-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/key-value/basic/index.html
  packages/core/src/tests/key-value/key-value.e2e.ts
  packages/core/src/tests/key-value/key-value.e2e.ts-snapshots/key-value-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/key-value/key-value.e2e.ts-snapshots/key-value-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/key-value-list.md
  packages/documentation/docs/controls/key-value.md
  packages/html-test-app/src/preview-examples/key-value-list-striped.html
  packages/html-test-app/src/preview-examples/key-value-list-with-custom-value.html
  packages/html-test-app/src/preview-examples/key-value-list-with-icon.html
  packages/html-test-app/src/preview-examples/key-value-list.html
  packages/html-test-app/src/preview-examples/key-value-with-custom-value.html
  packages/html-test-app/src/preview-examples/key-value-with-icon.html
  packages/html-test-app/src/preview-examples/key-value-with-label-left.html
  packages/html-test-app/src/preview-examples/key-value.html
  packages/react-test-app/src/preview-examples/key-value-list-striped.tsx
  packages/react-test-app/src/preview-examples/key-value-list-with-custom-value.tsx
  packages/react-test-app/src/preview-examples/key-value-list-with-icon.tsx
  packages/react-test-app/src/preview-examples/key-value-list.tsx
  packages/react-test-app/src/preview-examples/key-value-with-custom-value.tsx
  packages/react-test-app/src/preview-examples/key-value-with-icon.tsx
  packages/react-test-app/src/preview-examples/key-value-with-label-left.tsx
  packages/react-test-app/src/preview-examples/key-value.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/key-value-list-striped.vue
  packages/vue-test-app/src/preview-examples/key-value-list-with-custom-value.vue
  packages/vue-test-app/src/preview-examples/key-value-list-with-icon.vue
  packages/vue-test-app/src/preview-examples/key-value-list.vue
  packages/vue-test-app/src/preview-examples/key-value-with-custom-value.vue
  packages/vue-test-app/src/preview-examples/key-value-with-icon.vue
  packages/vue-test-app/src/preview-examples/key-value-with-label-left.vue
  packages/vue-test-app/src/preview-examples/key-value.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#547 feat(core/message-bar): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components/message-bar/message-bar.scss
  packages/core/src/components/message-bar/message-bar.tsx
  packages/core/src/components/message-bar/test/__snapshots__/message-bar.spec.tsx.snap
  packages/core/src/components/message-bar/test/message-bar.spec.tsx
Labels: semvers: patch

#548 feat(core/spinner): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components/spinner/spinner.scss
  packages/core/src/components/spinner/spinner.tsx
Labels: semvers: patch

#544 feat(core/drawer): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/drawer/drawer.scss
  packages/core/src/components/drawer/drawer.tsx
  packages/core/src/components/drawer/test/__snapshots__/drawer.spec.tsx.snap
  packages/core/src/components/drawer/test/drawer.spec.tsx
  packages/core/src/tests/drawer/drawer.e2e.ts
  packages/core/src/tests/drawer/drawer.e2e.ts-snapshots/drawer-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/drawer/drawer.e2e.ts-snapshots/drawer-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#550 feat(core/map-navigation): expose method to change visibility of sidebar
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/map-navigation/map-navigation.tsx
Labels: semvers: minor

#554 docs: remove duplicated sidebar entries
  packages/documentation/docs/grid/grid.md
  packages/documentation/sidebars.js
Labels: component: documentation

#567 chore: update to ix-icons 1.1.0
  packages/angular-test-app/package.json
  packages/angular/package.json
  packages/core/package.json
  packages/documentation/package.json
  packages/html-test-app/package.json
  packages/react-test-app/package.json
  packages/react/package.json
  packages/vue-test-app/package.json
  packages/vue/package.json
  yarn.lock
Labels: semvers: minor
