Repository siemens/ix, pull requests merged in 2023-07, with the labels that each got.

#615 docs(ag-grid|echarts): add license information
  packages/angular-test-app/src/preview-examples/aggrid.ts
  packages/documentation/docs/controls/charts/charts.md
  packages/documentation/docs/grid/grid.md
  packages/documentation/src/pages/index.tsx
  packages/html-test-app/src/preview-examples/aggrid.html
  packages/react-test-app/src/preview-examples/aggrid.tsx
  packages/vue-test-app/src/preview-examples/aggrid.vue
Labels: component: documentation

#617 fix(core/spinner): update secondary color
  packages/core/src/components/spinner/spinner.scss
  packages/core/src/tests/spinner/spinner.e2e.ts-snapshots/spinner-basic-1-chromium---theme-classic-dark-linux.png
Labels: semvers: patch

#620 fix(core/icon-button): deprecated size 32
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/icon-button/icon-button.tsx
Labels: component: documentation

#624 fix(core/date-picker): done button hidden
  packages/core/src/components/date-picker/date-picker.tsx
  packages/core/src/tests/date-picker/date-picker.e2e.ts-snapshots/date-picker-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/date-picker/date-picker.e2e.ts-snapshots/date-picker-basic-1-chromium---theme-classic-light-linux.png
  packages/html-test-app/src/preview-examples/datepicker-range.html
  packages/html-test-app/src/preview-examples/datepicker.html
Labels: semvers: patch

#603 feat(core/chip): enable shadow dom
  packages/core/component-doc.json
  packages/core/src/components/chip/chip-mixin.scss
  packages/core/src/components/chip/chip.scss
  packages/core/src/components/chip/chip.tsx
  packages/core/src/components/icon-button/icon-button.scss
  packages/core/src/tests/chip/chip.e2e.ts-snapshots/chip-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/chip/chip.e2e.ts-snapshots/chip-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/chip/chip.e2e.ts-snapshots/chip-custom-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/chip/chip.e2e.ts-snapshots/chip-custom-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#636 feat(core/expanding-search): migrate to shadow dom
  packages/core/component-doc.json
  packages/core/src/components/expanding-search/expanding-search.scss
  packages/core/src/components/expanding-search/expanding-search.tsx
  packages/core/src/components/expanding-search/test/__snapshots__/expanding-search.spec.tsx.snap
  packages/core/src/components/expanding-search/test/expanding-search.ct.ts
  packages/core/src/components/expanding-search/test/expanding-search.spec.tsx
Labels: semvers: major

#568 feat(core/toggle): component rework
  packages/angular-test-app/src/preview-examples/toggle-checked.ts
  packages/angular-test-app/src/preview-examples/toggle-indeterminate.ts
  packages/core/scss/theme/classic-dark/_borderRadius.scss
  packages/core/scss/theme/classic-dark/_color.scss
  packages/core/scss/theme/classic-light/_color.scss
  packages/core/src/components/toggle/toggle.scss
  packages/core/src/tests/toggle/basic/index.html
  packages/core/src/tests/toggle/disabled/index.html
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/toggle.md
  packages/html-test-app/src/preview-examples/toggle-checked.html
  packages/html-test-app/src/preview-examples/toggle-indeterminate.html
  packages/react-test-app/src/preview-examples/toggle-checked.tsx
  packages/react-test-app/src/preview-examples/toggle-indeterminate.tsx
  packages/vue-test-app/src/preview-examples/toggle-checked.vue
  packages/vue-test-app/src/preview-examples/toggle-indeterminate.vue
Labels: semvers: minor

#661 feat(core/group): migrate to shadow dom
  BREAKING_CHANGES.md
  packages/angular-test-app/src/preview-examples/group-context-menu.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/group-dropdown-item/group-dropdown-item.scss
  packages/core/src/components/group-dropdown-item/group-dropdown-item.tsx
  packages/core/src/components/group-item/group-item.scss
  packages/core/src/components/group-item/group-item.tsx
  packages/core/src/components/group/group-context-menu.scss
  packages/core/src/components/group/group-context-menu.tsx
  packages/core/src/components/group/group.scss
  packages/core/src/components/group/group.tsx
  packages/core/src/components/utils/shadow-dom.ts
  packages/core/src/tests/group/group.e2e.ts
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-item-selected-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-with-context-menu-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/group/group.e2e.ts-snapshots/group-with-context-menu-1-chromium---theme-classic-light-linux.png
  packages/core/stencil.config.ts
  packages/documentation/docs/controls/group.md
  packages/react/src/components.ts
  packages/vue/src/components.ts
Labels: semvers: major

#662 feat(core/toggle): migrate to shadow dom
  BREAKING_CHANGES.md
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/toggle/test/toggle.ct.ts
  packages/core/src/components/toggle/test/toggle.spec.ts
  packages/core/src/components/toggle/toggle.scss
  packages/core/src/components/toggle/toggle.tsx
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/toggle/toggle.e2e.ts-snapshots/toggle-disabled-1-chromium---theme-classic-light-linux.png
  packages/vue/src/components.ts
Labels: semvers: major

#655 fix(core/upload): drop while loading and input width
  packages/core/src/components/upload/upload.scss
  packages/core/src/components/upload/upload.tsx
  packages/core/src/tests/upload/upload.e2e.ts-snapshots/upload-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/upload/upload.e2e.ts-snapshots/upload-basic-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch
