Repository siemens/ix, pull requests merged in 2024-01, with the labels that each got.

#1022 fix(core/upload): replace class icons with ix-icon
  packages/core/src/components/upload/upload.scss
  packages/core/src/components/upload/upload.tsx
  packages/core/src/tests/upload/states/index.html
  packages/core/src/tests/upload/upload.e2e.ts
  packages/core/src/tests/upload/upload.e2e.ts-snapshots/upload-States-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/upload/upload.e2e.ts-snapshots/upload-States-1-chromium---theme-classic-light-linux.png
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/upload.tsx
Labels: semvers: patch

#1024 Issue rectified - The positions of html and ts code in documentation has been corrected
  packages/documentation/docs/controls/dropdown.md
Labels: component: documentation

#1036 Fix/tooltip positioning
  packages/core/src/components/tooltip/tooltip.tsx
Labels: semvers: patch

#1038 ci(deployment): replace theme download method
  .github/workflows/deploy-pages-daily.yml
  .github/workflows/deploy-pages.yml
Labels: component: documentation

#1040 fix(core/menu): adjust spacing of menu-button and app-switch
  packages/core/src/components/application-header/application-header.scss
  packages/core/src/components/menu/menu.scss
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-content-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-content-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-not-have-visual-regressions---svg-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-not-have-visual-regressions---svg-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-not-have-visual-regressions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application-header/application-header.e2e.ts-snapshots/application-header-basic-should-not-have-visual-regressions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-large-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-large-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-large-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/application/application.e2e.ts-snapshots/basic-navigation-large-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-large-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-large-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-large-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/basic-navigation/basic-navigation.e2e.ts-snapshots/basic-navigation-large-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-content-width-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/map-navigation/map-navigation.e2e.ts-snapshots/map-navigation-content-width-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-about-news/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-about-news/menu-about-news.e2e.ts-snapshots/menu-about-news-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-about/menu-about.e2e.ts-snapshots/menu-about-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-image-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-initials-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-no-dropdown-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-avatar/menu-about-avatar.e2e.ts-snapshots/menu-avatar-no-dropdown-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-label-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-label-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-switch-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu-settings/menu-settings.e2e.ts-snapshots/menu-settings-switch-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#1016 fix(core/modal): remove dialog on escape
  packages/core/src/components/modal/modal.tsx
  packages/core/src/tests/modal/modal.e2e.ts
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-close-on-Escape-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/modal/modal.e2e.ts-snapshots/modal-close-on-Escape-1-chromium---theme-classic-light-linux.png
Labels: semvers: patch

#988 docs(writing-style-guide): add getting started page
  packages/core/src/components/application-header/test/application-header.ct.ts
  packages/core/src/components/date-picker/test/date-picker.ct.ts
  packages/core/src/components/datetime-picker/test/datetime-picker.ct.ts
  packages/core/src/components/dropdown/test/dropdown.ct.ts
  packages/core/src/components/icon-button/test/icon-button.ct.ts
  packages/core/src/components/pagination/test/pagination.ct.ts
  packages/core/src/components/time-picker/test/time-picker.ct.ts
  packages/documentation/docs/language/writing-style-guide-getting-started.md
  packages/documentation/package.json
  packages/documentation/static/img/101.svg
  packages/documentation/static/img/capitalization.svg
  packages/documentation/static/img/like.svg
  packages/documentation/static/img/modal.svg
  packages/documentation/static/img/punctuation.svg
  yarn.lock
Labels: semvers: patch

#1043 feat(core/avatar): add user-info to dropdown
  packages/angular-test-app/src/preview-examples/application-header.html
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/avatar/avatar.scss
  packages/core/src/components/avatar/avatar.tsx
  packages/core/src/components/avatar/test/avatar.ct.ts
  packages/core/src/components/divider/divider.scss
  packages/core/src/tests/avatar/avatar.e2e.ts
  packages/core/src/tests/avatar/avatar.e2e.ts-snapshots/avatar-user-info-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/avatar/avatar.e2e.ts-snapshots/avatar-user-info-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/avatar/user-info/index.html
  packages/core/src/tests/dropdown-quick-actions/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/dropdown-quick-actions/dropdown-quick-actions.e2e.ts-snapshots/dropdown-quick-actions-basic-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/_avatar_code.md
  packages/documentation/docs/controls/application-frame/application-header.md
  packages/html-test-app/src/preview-examples/application-header.html
  packages/react-test-app/src/preview-examples/application-header.tsx
  packages/vue-test-app/src/preview-examples/application-header.vue
  packages/vue/src/components.ts
Labels: semvers: minor

#1054 fix(core/slider): use correct pointerup event
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/slider/test/slider.ct.ts
Labels: pull request affects patch version

#1051 fix(core/dropdown): use controller instance to handle dropdown instances
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/dropdown-button-icon.ts
  packages/angular-test-app/src/preview-examples/dropdown-button.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.ct.ts
  packages/core/src/components/toast/toast-utils.ts
  packages/core/src/tests/dropdown/dropdown.e2e.ts
  packages/core/src/tests/dropdown/dropdown.e2e.ts-snapshots/dropdown-tigger-events-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/dropdown/dropdown.e2e.ts-snapshots/dropdown-tigger-events-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/dropdown/trigger-events/index.html
  packages/vue/src/components.ts
Labels: pull request affects patch version

#1039 fix(toast): fixed initial async undefined error
  packages/core/src/components/toast/toast-container.tsx
Labels: pull request affects patch version
