Repository siemens/ix, pull requests merged in 2024-02, with the labels that each got.

#1067 fix: aggrid checkbox sizing
  packages/aggrid/scss/ix-aggrid.scss
Labels: type: bug, pull request affects patch version

#1060 fix(core/dropdown): check submenu item by interface
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/scss/_z-index.scss
  packages/core/src/components.d.ts
  packages/core/src/components/application-header/application-header.tsx
  packages/core/src/components/dropdown-item/dropdown-item.tsx
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.ct.ts
  packages/core/src/components/menu-avatar-item/menu-avatar-item.tsx
  packages/core/src/components/playground/playground.tsx
  packages/core/src/components/split-button-item/split-button-item.tsx
  packages/core/src/components/utils/internal/component.ts
  packages/core/src/components/utils/internal/index.ts
  packages/core/src/components/utils/make-ref.ts
  packages/vue/src/components.ts
  yarn.lock
Labels: pull request affects patch version

#1046 fix(core/radio-button): fix alignment of checked indicator
  packages/core/scss/components/_radiobuttons.scss
Labels: pull request affects patch version

#1070 fix(core/windows-doc-generation): fix for component-doc generation
  packages/core/stencil.config.ts
Labels: pull request affects patch version

#933 fix(core/menu-about): unwanted behavior on fast tab change
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/menu-about-item/menu-about-item.tsx
  packages/core/src/components/menu-about/menu-about.tsx
  packages/core/src/components/menu-settings-item/menu-settings-item.tsx
  packages/core/src/components/menu-settings/menu-settings.tsx
  packages/core/src/components/utils/menu-tabs/menu-tabs-fc.tsx
  packages/core/src/components/utils/menu-tabs/menu-tabs-utils.ts
  packages/vue/src/components.ts
Labels: pull request affects patch version

#989 New Sidepanel Component
  packages/angular-test-app/src/app/app-routing.module.ts
  packages/angular-test-app/src/app/app.module.ts
  packages/angular-test-app/src/preview-examples/pane-layout.html
  packages/angular-test-app/src/preview-examples/pane-layout.ts
  packages/angular-test-app/src/preview-examples/pane.html
  packages/angular-test-app/src/preview-examples/pane.ts
  packages/angular/src/components.ts
  packages/angular/src/declare-components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/pane-layout/pane-layout.scss
  packages/core/src/components/pane-layout/pane-layout.tsx
  packages/core/src/components/pane-layout/test/pane-layout.ct.ts
  packages/core/src/components/pane/pane.scss
  packages/core/src/components/pane/pane.tsx
  packages/core/src/components/pane/test/panes.ct.ts
  packages/core/src/components/playground/playground.tsx
  packages/core/src/tests/panes/basic/index.html
  packages/core/src/tests/panes/layout/index.html
  packages/core/src/tests/panes/panes.e2e.ts
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-collapsed-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-collapsed-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-changed-layout-floating-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-changed-layout-floating-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-collapsed-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-collapsed-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-left-expanded-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-floating-left-expanded-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-collapsed-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-collapsed-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-collapsed-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-collapsed-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-left-expanded-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-layout-inline-left-expanded-mobile-1-chromium---theme-classic-light-linux.png
  packages/documentation/docs/controls/_panes_code.md
  packages/documentation/docs/controls/_panes_styleguide.md
  packages/documentation/docs/controls/panes.md
  packages/html-test-app/src/preview-examples/pane-layout.html
  packages/html-test-app/src/preview-examples/pane.html
  packages/react-test-app/src/main.tsx
  packages/react-test-app/src/preview-examples/pane-layout.tsx
  packages/react-test-app/src/preview-examples/pane.tsx
  packages/react/src/components.ts
  packages/vue-test-app/src/Root.vue
  packages/vue-test-app/src/preview-examples/pane-layout.vue
  packages/vue-test-app/src/preview-examples/pane.vue
  packages/vue/src/components.ts
Labels: pull request affects minor version

#1089 Fix/card selected hover
  packages/angular/src/components.ts
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/action-card/action-card.scss
  packages/core/src/components/action-card/action-card.tsx
  packages/core/src/components/card/card.scss
  packages/core/src/components/card/card.tsx
  packages/core/src/components/push-card/push-card.scss
  packages/core/src/tests/card/basic/index.html
  packages/core/src/tests/card/card.e2e.ts
  packages/core/src/tests/card/card.e2e.ts-snapshots/card-basic-should-have-selected-state-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/card/card.e2e.ts-snapshots/card-basic-should-have-selected-state-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/card/card.e2e.ts-snapshots/card-basic-should-not-have-visual-regressions-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/card/card.e2e.ts-snapshots/card-basic-should-not-have-visual-regressions-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/card/selected/index.html
  packages/documentation/docs/controls/grid.md
  packages/vue/src/components.ts
Labels: pull request affects minor version

#1086 Fix/dropdowns
  packages/core/component-doc.json
  packages/core/src/components.d.ts
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/dropdown/test/dropdown.ct.ts
  packages/react-test-app/src/main.tsx
Labels: pull request affects patch version

#1093 Fix/dropdown close on escape
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/test/dropdown.ct.ts
Labels: pull request affects patch version

#1080 fix(core/modal): fixed closing modal issue when press space or enter
  packages/core/src/components/modal/modal.tsx
Labels: pull request affects patch version

#1099 fix(react|vue): define internal components
  packages/react/src/internal-components.ts
  packages/vue/src/internal-components.ts
Labels: pull request affects patch version

#1104 fix(core/dropdown): check against undefined access
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/test/dropdown-controller.spec.ts
Labels: pull request affects patch version

#1112 fix(core/burger-menu): a11y expand state
  packages/core/src/components/menu/burger-menu.scss
  packages/core/src/components/menu/burger-menu.tsx
  packages/core/src/components/menu/test/menu.ct.ts
Labels: pull request affects patch version

#1118 fix(core/tooltip): remove direct constructor access
  packages/angular-test-app/src/preview-examples/tooltip.html
  packages/core/component-doc.json
  packages/core/package.json
  packages/core/src/components/tooltip/test/tooltip.ct.ts
  packages/core/src/components/tooltip/tooltip.tsx
  packages/documentation/docs/controls/tooltip.md
  packages/html-test-app/src/preview-examples/tooltip.html
  packages/react-test-app/src/preview-examples/tooltip.tsx
  packages/vue-test-app/src/preview-examples/tooltip.vue
  yarn.lock
Labels: pull request affects patch version

#1119 fix(core/panes): expanded and slot error
  packages/core/src/components/pane-layout/pane-layout.tsx
  packages/core/src/components/pane-layout/test/pane-layout.ct.ts
  packages/core/src/components/pane/pane.scss
  packages/core/src/components/pane/pane.tsx
  packages/core/src/tests/panes/basic/index.html
  packages/core/src/tests/panes/panes.e2e.ts
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-mobile-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-basic-floating-no-collapsed-state-expanded-mobile-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-slot-correctly-toggles-while-being-collapsed-through-content-click-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/panes/panes.e2e.ts-snapshots/pane-slot-correctly-toggles-while-being-collapsed-through-content-click-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/panes/slot/index.html
Labels: pull request affects patch version

#1110 fix(core/menu-category): allow empty icon as menu-category-item
  packages/core/component-doc.json
  packages/core/src/components/menu-category/menu-category.scss
  packages/core/src/components/menu-category/menu-category.tsx
  packages/core/src/components/menu-category/test/menu-category.ct.ts
  packages/core/src/components/menu-item/menu-item.scss
  packages/core/src/components/menu-item/menu-item.tsx
  packages/core/src/tests/menu/basic/index.html
  packages/core/src/tests/menu/link/index.html
  packages/core/src/tests/menu/menu.e2e.ts
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-lg---no-default-icon-on-second-level-visible-ellipsis-for-category-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-lg---no-default-icon-on-second-level-visible-ellipsis-for-category-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-md---no-default-icon-on-second-level-scaling-for-popup-window-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-md---no-default-icon-on-second-level-scaling-for-popup-window-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-link---should-render-menu-items-with-a-href-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-link---should-render-menu-items-with-a-href-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/should-render-menu-items-with-a-href-1-chromium---theme-classic-light-linux.png
Labels: pull request affects patch version

#1102 fix(core/menu-category): fix unwanted behavior with active element
  packages/core/src/components/menu-category/menu-category.scss
  packages/core/src/components/menu-category/menu-category.tsx
  packages/core/src/components/menu-category/test/menu-category.ct.ts
  packages/core/src/tests/menu/active/index.html
  packages/core/src/tests/menu/menu.e2e.ts
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-basic-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-category-open-on-expand-when-initially-closed-and-activated-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-category-open-on-expand-when-initially-closed-and-activated-1-chromium---theme-classic-light-linux.png
Labels: pull request affects patch version

#1113 fix(core/menu-avatar-item): use host for trigger target
  packages/core/src/components/dropdown/dropdown-controller.ts
  packages/core/src/components/dropdown/dropdown.tsx
  packages/core/src/components/menu-avatar-item/test/menu-avatar-item.ct.ts
Labels: pull request affects patch version

#1121 fix(core/menu): fix theme switching icon
  packages/core/src/components/menu/menu.tsx
  packages/core/src/tests/menu/menu.e2e.ts
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-toggle---check-icon-functionality-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/menu/menu.e2e.ts-snapshots/menu-toggle---check-icon-functionality-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/menu/toggle/index.html
Labels: pull request affects patch version

#1116 fix(core/menu-avatar-item): use correct theme color
  packages/core/src/components/menu-avatar-item/menu-avatar-item.scss
Labels: pull request affects patch version

#1124 fix(angular): icon size property missing in wrapper generation
  packages/angular/src/ix-icon.ts
Labels: pull request affects patch version

#1125 fix(core/blind): refactor header to not use z-index
  packages/core/src/components/blind/blind.scss
  packages/core/src/components/blind/blind.tsx
  packages/core/src/tests/blind/blind.e2e.ts
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-custom-header-1-chromium---theme-classic-dark-linux.png
  packages/core/src/tests/blind/blind.e2e.ts-snapshots/blind-custom-header-1-chromium---theme-classic-light-linux.png
  packages/core/src/tests/blind/custom-header/index.html
Labels: pull request affects patch version

#1128 chore: bump ix version to 2.1.1
  CHANGELOG.md
  package.json
  packages/aggrid/package.json
  packages/angular-test-app/package.json
  packages/angular/package.json
  packages/core/package.json
  packages/documentation/docs/controls/modal.md
  packages/documentation/docs/installation/CHANGELOG.md
  packages/documentation/package.json
  packages/echarts/package.json
  packages/html-test-app/package.json
  packages/react-test-app/package.json
  packages/react/package.json
  packages/vue-test-app/package.json
  packages/vue/package.json
Labels: pull request affects patch version

#1132 fix(core/dropdown): add null check
  packages/core/src/components/dropdown/dropdown.tsx
Labels: pull request affects patch version
